easy_admin:
    site_name: 'Administration'
    user:
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - email
                    - password

        Skill:
            class: App\Entity\Skill
            form:
                fields:
                    - name
                    - level

        WorkFilter:
            class: App\Entity\WorkFilter
            form:
                fields:
                    - name

        Experience:
            class: App\Entity\Experience
            form:
                fields:
                    - name
                    - { property: 'description', type: 'text-editor' }
                    - contract
                    - dateRealization

        work:
            class: App\Entity\Work
            form:
                fields:
                    - title
                    - { property: 'description', type: 'text-editor' }
                    - filters
                    - dateRealization

        version:
            class: App\Entity\Version
            form:
                fields:
                    - name
                    - date
                    - major
                    - { property: 'description', type: 'text-editor' }
                    - tags

        VersionTag:
            class: App\Entity\VersionTag
            form:
                fields:
                    - name
                    - { property: 'color', type: 'color' }


        page:
            class: App\Entity\Page
            form:
                fields:
                    - name
                    - metaTitle
                    - metaDescription
                    - data

