easy_admin:
    site_name: 'Administration'
    user:
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - email
                    - password

        Skill:
            class: App\Entity\Skill
            form:
                fields:
                    - name
                    - level

        WorkFilter:
            class: App\Entity\WorkFilter
            form:
                fields:
                    - name

        Experience:
            class: App\Entity\Experience
            form:
                fields:
                    - name
                    - description
                    - dateRealization

        work:
            class: App\Entity\Work
            form:
                fields:
                    - title
                    - description
                    - filters
                    - dateRealization

